### ISSUE TITLE
[Enhancement] Stack repeating lines.

### ISSUE THREAD

**Issue by Rallik-Pog** [Nickert1337/powbot_logs#1]
Get alot of spam from the EGL_emulation eglMakeCurrent

**Comment by Nickert1337** [comment]
Do you have the **blacklisted_lines.ini** file next to your Powbot.Logs.exe? Try adding those two lines to that file. I will add them to the .ini file for next release.

See:
https://github.com/Nickert1337/powbot_logs/tree/main#removing-spammy-lines-from-the-log

**Comment by Rallik-Pog** [comment]
Ah my bad, I did not. I also did not read the updated readme.
